[project]
name = "study-buddy-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.2.0",
    "google-generativeai>=0.8.4",
    "gradio>=5.16.2",
    "python-dotenv>=1.0.1",
]
